M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-08-06T19:27:35-0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-06T19:27:35-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X7.763Y-2.1711
X7.8811Y-2.1711
M30
